### ISSUE TITLE
编译过程中的bug

### ISSUE THREAD

**Issue by frank2002** [tete1030/openwrt-fastbuild-actions#13]
![image](https://user-images.githubusercontent.com/20471771/76866751-8cd3c900-689f-11ea-9ec1-db99a939f63e.png)
![image](https://user-images.githubusercontent.com/20471771/76866755-8e04f600-689f-11ea-8f76-8fa6b5211524.png)
我不知道这是什么原因，本机上是可以编译成功的，这个模板怎么都不行。
还望解答，谢谢！

**Comment by tete1030** [comment]
把patches/004-extroot-for-x86.patch删掉吧，这个patch我已经提交到coolsnowwolf/lede里了，现在两处重复了

**Comment by frank2002** [comment]
你好，谢谢你的解答
但是这次我用squanfs格式不报错，但是编译出来的文件仍然只有15字节。如果用ext4格式，爆出如下错误。
![image](https://user-images.githubusercontent.com/20471771/76916401-457b2600-68fb-11ea-8928-b401066e074d.png)
还望解答，谢谢！

**Comment by tete1030** [comment]
请把你每个错误的run URL贴出来 方便查看

**Comment by frank2002** [comment]
https://github.com/frank2002/openwrt-fastbuild-actions/runs/515364880?check_suite_focus=true
https://github.com/frank2002/openwrt-fastbuild-actions/runs/515294203?check_suite_focus=true
万分感谢

**Comment by tete1030** [comment]
第一个问题，显示15bytes，请直接忽略。实际文件大小不止15bytes，这是github的bug
关于第二个问题ext4报错，这好像是因为runner空间不足了，不像是从squashfs切换ext4导致的
你编译的包看起来比较多，incremental building的情况下整个builder会随着每次编译越来越大。临时的解决方案是删除更多的内容，参考https://github.com/tete1030/openwrt-fastbuild-actions/issues/12#issuecomment-596165887

下一个版本出来后空间的情况会有所优化，但是github actions的空间并不算特别充足，尤其在使用docker的情况下，每次创建一个image需要临时占用两倍的空间，容易出现空间不足

**Comment by frank2002** [comment]
解决了，谢谢
