### ISSUE TITLE
dev分支 OPT_UPDATE_REPR OPT_UPDATE_FEEDS这些在哪里设置？

### ISSUE THREAD

**Issue by ghost** [tete1030/openwrt-fastbuild-actions#15]
如题 dev分支 OPT_UPDATE_REPR OPT_UPDATE_FEEDS这些在哪里设置？ 还是说精简掉了 默认启用。

**Comment by tete1030** [comment]
可以在push前最后一个commit的message包含`#update_repo#`和`#update_feeds#`字符串。或通过deploy事件、repo_dispatch事件指定（在payload中指定`{"target": "你的profile名", "update_repo": true}`）

deploy事件和repo_dispatch事件的激活方法可以参考readme

dev分支和sample分支相比master有了不少变化，但是目前README目前没有完成更新（因为懒XD），因此还没合并到master

**Comment by ghost** [comment]
如何让他默认启用。我每天cron需要定时

**Comment by ghost** [comment]
还有很不理解 OPT_USE_BASE  是干什么的

**Comment by tete1030** [comment]
现在可能没有办法，我正准备支持把这些选项放入各profile的settings.ini中固定

**Comment by tete1030** [comment]
> 还有很不理解 OPT_USE_BASE 是干什么的

use_base其实是以前旧版本里re-link的意思，就是使用第一次编译的builder作为基础（而不是上一次的builder），其实这个功能用处不大。设置这个功能主要是考虑到编译次数越来越多时，docker层数也越来越多，image会比较大，用这种方式可以避免完全rebuild，又可以减小builder size

**Comment by ghost** [comment]
由哪个变量控制   可以在适当的位置给他赋值就行了吧

**Comment by tete1030** [comment]
和update_feeds、update_repo一样的。
很多OPT_*开头的，设置选项的时候可以写成对应的无OPT_小写。比如OPT_USE_BASE转换成json选项：`{"use_base": true}`

**Comment by ghost** [comment]
> 和update_feeds、update_repo一样的。
> 很多OPT_*开头的，设置选项的时候可以写成对应的无OPT_小写。比如OPT_USE_BASE转换成json选项：`{"use_base": true}`

放在哪里比较好

**Comment by tete1030** [comment]
> 可以在push前最后一个commit的message包含`#update_repo#`和`#update_feeds#`字符串。或通过deploy事件、repo_dispatch事件指定（在payload中指定`{"target": "你的profile名", "update_repo": true}`）
> 
> deploy事件和repo_dispatch事件的激活方法可以参考readme
> 
> dev分支和sample分支相比master有了不少变化，但是目前README目前没有完成更新（因为懒XD），因此还没合并到master

**Comment by ghost** [comment]
cron怕是不行。。算了 
squash.yml 这个是专门缩小docker 镜像的大小的吧 
以什么依据判断的 翻了你的action好多 都是跳过。

**Comment by ghost** [comment]
cron怕是不行。。算了 
squash.yml 这个是专门缩小docker 镜像的大小的吧 
以什么依据判断的 翻了你的action好多 都是跳过。

**Comment by tete1030** [comment]
> > 和update_feeds、update_repo一样的。
> > 很多OPT_*开头的，设置选项的时候可以写成对应的无OPT_小写。比如OPT_USE_BASE转换成json选项：`{"use_base": true}`
> 
> 放在哪里比较好

如果想让cron默认启用的话，很遗憾现在还不行。我近期更新了可以告诉你。

对，squash是用来压缩的所有docker层为一层的，在层数比较多的时候很必要。“action很多是跳过”，你指的是运行到check if skip target即跳过吗？确实是这样，主要是github actions的触发方式让我很难找到合适的办法能同时结合multi-profile特性和changed file detection特性。现在的实现方法其实蛮粗暴，每个target都会触发，然后快速检测是否需要跳过

**Comment by tete1030** [comment]
> cron怕是不行。。算了
> squash.yml 这个是专门缩小docker 镜像的大小的吧
> 以什么依据判断的 翻了你的action好多 都是跳过。

哦，你意思是squash。由于squash和building都利用了deployment事件作为触发标准，我很多时候是利用该事件手动触发building的，不可避免地squash也被激活。这个时候squash job会检测当前的任务是build还是squash以确定要不要跳过 （这个现象后面更新利用最新的Github Actions API可以避免）

squash的执行标准是一个特定的层数作为阈值。超过阈值即执行（可能在building前执行，也可能自动定时检测时执行

**Comment by ghost** [comment]
![0%X%WG6I4W3OQ9Q6(Q)I}MD](https://user-images.githubusercontent.com/31695447/78258965-9bbcab80-752e-11ea-94bb-de174bab7824.png)
![VW)${{TY)5SN8ME71MJ6 9](https://user-images.githubusercontent.com/31695447/78258976-9eb79c00-752e-11ea-9145-7ed39c93ad54.png)
我又看了以下 我只要在读取变量之前重新给 OPT_UPDATE_REPR ，OPT_UPDATE_FEEDS这两个值赋值的话 那就可以默认开启了吧 。

这个实现也比较简单吧。 yml里面写个变量，在这里面写个读取数值的。就能实现自主控制了吧。
至于 通过“最后一个commit的message包含#update_repo#和#update_feeds#字符串”那个代码 可以放在这之后，yml里面选项设置优先级高 yml里面开了就不管他了，没开再看个commit的message
有没有包含#update_repo#和#update_feeds# 字段就可以了吧 

我个人觉得这个很是可行 和你master分支是一样逻辑

**Comment by tete1030** [comment]
注意不是OPT_UPDATE_REPR，是OPT_UPDATE_REPO

如果你急用，在scripts/host/init_runner.sh的末尾设置这些参数值，然后_set_env它们。像这样
![image](https://user-images.githubusercontent.com/4312115/78260666-c7d92c00-7530-11ea-9839-4a9561b8665d.png)

我要想更新也很容易，只是现在有些别的更新在进行，到时候一起push

**Comment by ghost** [comment]
好的 非常感谢
