### ISSUE TITLE
dev分支 Organize files 这个运行应该加个判断

### ISSUE THREAD

**Issue by ghost** [tete1030/openwrt-fastbuild-actions#16]
![CXK`EY9{~7)5{R2`J65DV`K](https://user-images.githubusercontent.com/31695447/78246020-0cf26380-751b-11ea-8f80-0dd45a142935.png)
 [Failure/Debug] Wait for SSH connection (timeout 30min) 这个错误 
Organize files依旧会执行 由于echo "::set-output name=status::success"
后面的都会挨个执行

**Comment by tete1030** [comment]
这个是预期行为。以前这么做是为了避免某个小错误导致已编译好的文件不能保留下来，因此不管出错与否都会执行organize和upload操作（反正这部分操作没什么额外成本）。如果不想继续可以直接取消当前job

**Comment by ghost** [comment]
明白了 那dev分支 opt_update_feed 和那个opt_update_repo是默认启用的么。
还有不明白default 目录为什么不能删 ，不能删除的话 可以做成一个通用的
比如说一个patches 要对所有机型生效，这样写一个就好了。现在是各自论各自的。每个都要写一个

**Comment by tete1030** [comment]
如果不想要default，default可以清空，但是目前目录不能删，我会修复一下这个。如果要让patches对所有机型生效，就放在default里，它会和各个profile自己的patches合并（如果文件不重名就不会互相覆盖）。但是对于settings.ini，custom.sh和packages.txt，如果各自profile中存在它，目前的方法是直接覆盖来自default的对应文件。

这里确实存在不一致，我正在考虑怎么做才是最有效的
