### ISSUE TITLE
编译好估计 之后 上传 到docker   出现了这个错误 latest-inc: not found

### ISSUE THREAD

**Issue by mingxiaoyu** [tete1030/openwrt-fastbuild-actions#17]
latest-inc: digest: sha256:d6637b8e0adb4115e7b4224c316a3af01c0627cf9eec3ab22d64182ad9a8f26f size: 1997
docker.io/***/openwrt_phicomm_n1:latest-inc: not found
我查看了下docker hub  , 这个tag 是存在的

https://github.com/mingxiaoyu/openwrt-fastbuild-actions/runs/905189314?check_suite_focus=true

**Comment by tete1030** [comment]
docker hub用户名内包含了任何非英文和数字字符吗？这错误有点奇怪，怀疑是偶然的docker服务器问题。不过出错的不是什么关键步骤，你可以让它忽略错误：
在scripts/cisteps/build-openwrt/13-upload_builder.sh
最后几行改成
```bash
if [ "x${OPT_REBUILD}" = "x1" ]; then
  // 加上最后的" || true"
  create_remote_tag_alias "${BUILDER_IMAGE_ID_INC}" "${BUILDER_IMAGE_ID_BASE}" || true
fi
```

EDIT: 这个错误的唯一影响是使rebase功能失效。但是这个功能很不常用，需要完全重编译时直接rebuild即可，不需要rebase

**Comment by mingxiaoyu** [comment]
用户名是全英文  
openwrt_phicomm_n1:latest-inc
在docker hub 里有这个image 。大小6.4G。

随便问下 下次运行是不是会把 旧的image删掉？？

**Comment by tete1030** [comment]
新的image会覆盖旧的

**Comment by tete1030** [comment]
你再触发一次新的编译试试，再有问题我研究下怎么回事

**Comment by mingxiaoyu** [comment]
是用
if [ "x${OPT_REBUILD}" = "x1" ]; then
  // 加上最后的" || true"
  create_remote_tag_alias "${BUILDER_IMAGE_ID_INC}" "${BUILDER_IMAGE_ID_BASE}" || true
fi
还是 不修改直接触发？？？  无论哪种方式，我在你回复后，都会帮你测试次。 嘻嘻

@tete1030

**Comment by tete1030** [comment]
都可以，什么都不影响。改这条只影响github actions的外观显示结果，改完后不会显示成错误，但是日志仍能看到

**Comment by mingxiaoyu** [comment]
> 都可以，什么都不影响。改这条只影响github actions的外观显示结果，改完后不会显示成错误，但是日志仍能看到

好滴 晚上到家在测试吧。。公车 手机伤不起

**Comment by mingxiaoyu** [comment]
再次运行没问题
