### ISSUE TITLE
内容越少，问题越严重。。。🤪

### ISSUE THREAD

**Issue by adaaaaaa** [tete1030/openwrt-fastbuild-actions#9]
Init build env：
Deleting files, please wait ...
##[error]The operation was canceled.

这是怎么肥事？

**Comment by tete1030** [comment]
![image](https://user-images.githubusercontent.com/4312115/71715652-181af200-2e4d-11ea-8405-254aa6befd35.png)

你这个错误日志，并不是这次的错误日志，其实是上次的（上次编译你自己取消了）。

这次实际上没有发生错误，只是因为没有任何job被启动，显示了一个叉。当你打开日志界面时，由于没有任何job，自动跳到了上次的编译日志

无job是因为你的job没有开启对应的if。。。。if也要设置schedule事件

**Comment by tete1030** [comment]
我之后还是把每个job的if写完整吧，反正只要不设置"on:"也不会触发。确实不能要求每个使用者完全了解github actions的语法

**Comment by adaaaaaa** [comment]
> 这次实际上没有发生错误，只是因为没有任何job被启动，显示了一个叉。当你打开日志界面时，由于没有任何job，自动跳到了上次的编译日志


谢谢大佬。。。那这样不是要每周都提醒我一次？

**Comment by tete1030** [comment]
schedule是你自己打开的吧？
你要么在job的if里设置schedule，那么每次提醒你的就是编译成功而不是编译失败的消息
如果不需要，把schedule注释掉就不会提醒你了
